version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: taskpulse-postgres
    environment:
      POSTGRES_DB: taskpulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Relevante@2026
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
